# Generated by Django 3.2 on 2021-05-14 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nlw1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectitem',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/items/%Y/%m/%d/'),
        ),
    ]
